### PR TITLE
run tests with next 15, bump peerDependency

### PR DESCRIPTION
**Pull request by phryneas**

### CODE REVIEW

**Comment by The-Code-Monkey** [comment]
@phryneas thank you for this, just made a PR myself and realised you had beat me to it by 1 minute

**Comment by phryneas** [comment]
@The-Code-Monkey Thank you for opening that other PR!

I'll probably have to tweak a few more things, so I hope it's okay if we leave things to this PR for now, okay? :)

**Comment by The-Code-Monkey** [comment]
@phryneas yeah thats fine, hopefully this is pretty straight forwards though and not much needs changing. I use the nextjs experimental package at work so would be nice to be able to update as soon as. but not a big rush.

**Comment by phryneas** [comment]
Seems that at least some things in our tests need to change due to breaking Next.js changes.

**Comment by The-Code-Monkey** [comment]
Ah yeah headers, cookies, params are now all async. that will probably be the biggest change.

**Comment by phryneas** [comment]
I wish it were
https://x.com/phry/status/1848658202805641322

**Comment by The-Code-Monkey** [comment]
Oh fun. well it was going to break some packages. strange that it went from error to undefined though

**Comment by phryneas** [comment]
Well, that's now all green. I'll take the win and get this released :)

**Comment by phryneas** [comment]
Released here: https://github.com/apollographql/apollo-client-nextjs/releases/tag/v.0.11.5

**Pull request merged**
