### PR TITLE
Update peer deps for React 19 compatibility

### PR DESCRIPTION
**Pull request by nphmuller**
Fixes resolve error in npm.

Just like https://github.com/apollographql/apollo-client/pull/12175/commits/205276b7f4984d087cd1087999a45bf8fbcffbf2

### CODE REVIEW

**Comment by phryneas** [comment]
Thank you for the PR! I'll have to do a bunch of these over the day, so please be a bit patient, it might take a few hours :)

**Comment by nphmuller** [comment]
No worries. Thank you!

**Comment by phryneas** [comment]
Let's see what the tests say with this.

**Comment by phryneas** [comment]
That's a bit more additional stuff than I had anticipated - I'll move that out into a separate PR :)

**Comment by phryneas** [comment]
Merging this one here already, continuing in the next PR :)

**Pull request merged**
